### ISSUE TITLE
Spam Filtering

### ISSUE THREAD

**Issue by maitreyie-chavan** [rtCamp/px-wp-insights#110]
Based on the Escalation Path decided, also incorporate necessary measures to help reduce/filter the Spam

**Comment by dhaval-parekh** [comment]
To prevent bulk requests from any sites or DDoS attacks. We have implemented IP-based request rate limits. For that, we used [Adonis throttle](https://github.com/masasron/adonis-throttle) library.

Current Rate limits.

For the below endpoint, the Rate limit is set to **10 requests per minute**.
- /authenticate/google
- /authenticated/google

For the below endpoint, the Rate limit is set to **30 requests per minute**.
- /admin
- /api/v1

There is **no limit** on the below endpoints.
- /
- /logout

**Note**: Rate limit is based on IP.

**Comment by westonruter** [comment]
> * /admin

This could be removed at this time.

**Comment by dhaval-parekh** [comment]
I have removed the rate limit on `/admin/` endpoints.

**Comment by dhaval-parekh** [comment]
Implementation is completed in #144
