### ISSUE TITLE
AMP-WP Plugins "Send Diagnostic Data" Feature

### ISSUE THREAD

**Issue by rahul286** [rtCamp/px-wp-insights#116]
Based on the [discussion](https://docs.google.com/document/d/1OXuRPzDJP_Z6OMKQ53S_5RVYM6ZF6RUp3xixyh6aGFs/edit) we have decided to decouple support infrastructure completely at the moment.

As of now, we will be adding:

**WordPress Dashboard ➞ AMP-WP  Menu ➞ Support (new submenu page)**

It will have the following:

- [x] A button to "Send Diagnostic Data" data. When data is sent, the AMP Comp DB infra returns a UUID. We will save these UUIDs with data/time (using WP sites timezone). 
- [ ] A list of past UUIDs with date & time
- [x] Helpful text which explains what is being sent, why, and how it can be used? Assigned to @rahul286 

The newly added support page is reachable through other areas in WordPress as listed below (based on https://github.com/ampproject/amp-wp/issues/5939):

- [x] **AMP admin menu dropdown on frontend**

New link here labeled"Send Diagnostic Data"
![Screenshot_2021-03-24_at_8_09_54_PM](https://user-images.githubusercontent.com/4115/112332584-ddb2a480-8cdf-11eb-9189-10f3690e761c.jpg)

- [x] Validated URL screen

- [x] In the list view (Before "Forget" menu":

![Screenshot_2021-03-24_at_8_15_04_PM](https://user-images.githubusercontent.com/4115/112332820-118dca00-8ce0-11eb-8dc0-11c67a75b214.jpg)

- [x] Single view

![Screenshot_2021-03-24_at_8_14_24_PM](https://user-images.githubusercontent.com/4115/112333102-4ef25780-8ce0-11eb-946b-ceb2a78fbe58.jpg)

## The data being sent with Send Diagnostic Data

WordPress Site Health and AMP Settings will be always included. 

If a single post id is present on the AMP support page (new menu item) we will include AMP validated URL data for that one particular URL.

Otherwise, we will include one sample URL for each post type using the existing function.

**Comment by pradeep910** [comment]
@pdclark Here is the function to get limited urls from each CPT - https://github.com/ampproject/amp-wp/blob/89a22586151ee3b3acec3aa3fcca0049d158f2e3/src/Validation/ScannableURLProvider.php#L38-L116

cc @dhaval-parekh @rahul286

**Comment by gagan0123** [comment]
For changing number of AMP URLs that are validated per post type, we have a filter `amp_url_validation_limit_per_type`

**Comment by pdclark** [comment]
### Admin screen with summary & Google styles...
![Screen Shot 2021-04-03 at 10 05 12 PM](https://user-images.githubusercontent.com/126889/113499161-abb3f600-94c8-11eb-96d3-b25da91e2f5a.png)

![Screen Shot 2021-04-03 at 9 58 53 PM](https://user-images.githubusercontent.com/126889/113499073-cb96ea00-94c7-11eb-9589-ffe434c4546b.png)

POST to node server still timing out at the moment @gagan0123 @dhaval-parekh 

https://github.com/rtCamp/amp-wp/tree/feature/send-button

**Comment by gagan0123** [comment]
@pdclark The UUID integration that we discussed during last call is still pending, so the timeout is still there.

Here's that issue for reference
https://github.com/rtCamp/amp-compatibility/issues/115

**Comment by rahul286** [comment]
@pdclark 

wp.org https://wordpress.org/support/plugin/amp/
gh https://github.com/ampproject/amp-wp/issues

**Comment by pdclark** [comment]
![amp-send-data](https://user-images.githubusercontent.com/126889/113591368-a8179080-95e8-11eb-8469-2679a4cc99e1.gif)

**Comment by pdclark** [comment]
error_log data added per meeting request.
@gagan0123 @dhaval-parekh

**Comment by maitreyie-chavan** [comment]
Closing this issue as we have now released this feature recently.
