### ISSUE TITLE
Add Active theme details in detailed Report 

### ISSUE THREAD

**Issue by milindmore22** [rtCamp/px-wp-insights#171]
Can we please add a section for “Active theme” in UUID Report on Adonis Dashboard, Make sure to add the parent theme section too in case their current Active theme is child

![image](https://user-images.githubusercontent.com/1132541/120684895-df0d0400-c4bc-11eb-9c32-efd624a18b1d.png)

**Comment by milindmore22** [comment]
@dhaval-parekh are you able to fetch parent theme details? or just the name of parent theme?

**Comment by maitreyie-chavan** [comment]
Active theme details are now available in the report

<img width="1170" alt="Screenshot 2021-12-30 at 1 09 44 AM" src="https://user-images.githubusercontent.com/20221326/147697719-226b1f59-ff7b-4ffe-94b2-8c5c9227e1d4.png">
