### ISSUE TITLE
Update copy text content to Copied on click

### ISSUE THREAD

**Issue by milindmore22** [rtCamp/px-wp-insights#181]
Can we please update link "copy" UUID code "copied" on click or any kind of notification like ✅   or tooltip notifying users that UUID is copied?

![image](https://user-images.githubusercontent.com/1132541/121347542-f2005800-c944-11eb-9746-db495a1d7c00.png)

**Comment by maitreyie-chavan** [comment]
This has been addressed with the new UI change 


<img width="509" alt="Screenshot 2021-12-30 at 1 08 09 AM" src="https://user-images.githubusercontent.com/20221326/147697597-84843b67-dd20-4f8a-8a1c-2ea8f793ac64.png">
