### ISSUE TITLE
Ability to export user submitted data to a csv file.

### ISSUE THREAD

**Issue by milindmore22** [rtCamp/px-wp-insights#182]
Whatever use submit using send diagnostic button in a csv file.

It can be implemented as an individual or batch export 

1) Add sort so only submitted data is can be selected not the ad-hoc or synthetic data
![image](https://user-images.githubusercontent.com/1132541/121353219-3ee72d00-c94b-11eb-9056-d878d34eae0e.png)

2) Add download ALL button for batch export, please add a date selector so we can export date in-between two dates

![image](https://user-images.githubusercontent.com/1132541/121353036-1101e880-c94b-11eb-870f-3fd549b6298c.png)

3) Individual data export

![image](https://user-images.githubusercontent.com/1132541/121353327-5e7e5580-c94b-11eb-8d97-e67f8b7c8002.png)

**Comment by dhaval-parekh** [comment]
Hey @milindmore22 ,

Regarding download options on the listing page, For each request, we can only add the detail for site info, AMP settings, active themes, and active plugins (In JSON format). However, there won't be validated URL, error, and its source detail.

Regarding the download option on the single report page, Can you please explain in which format the report needs to be downloaded?

**Comment by milindmore22** [comment]
@ThierryA Can you please add your inputs for data export, How about we export the whole export as JSON instead of a CSV file?

cc: @bethanylang

**Comment by dhaval-parekh** [comment]
@milindmore22 

I have added an option to export records. Please have a look and let me know if anything needs to change.

Link: https://insights.amp-wp.org/admin/report 

<img width="681" alt="image" src="https://user-images.githubusercontent.com/8168027/121848221-5c2f4900-cd07-11eb-8aff-eba62e1d6656.png">

**Comment by ThierryA** [comment]
@dhsathiya I don't really a useful use case to be able to export data on our side and can't recall discussing this. Perhaps something you discussed with @bethanylang?

**Comment by dhsathiya** [comment]
@ThierryA seems like you meanr to tag @dhaval-parekh in https://github.com/rtCamp/amp-compatibility/issues/182#issuecomment-860449648

**Comment by ThierryA** [comment]
Yep, thanks for the heads up :)

**Comment by bethanylang** [comment]
@ThierryA Apologies, I think I must have misunderstood here. I have a note from our discussion about this tool that you were interested in ensuring that there was some kind of export to CSV functionality, which I gathered would help with getting info into the trix. 

That said, even without it being a requirement on your side, I do think this is still a nice thing to have as an easy way to get the data out for any possible troubleshooting or reporting.

**Comment by maitreyie-chavan** [comment]
The option to export records in CSV format was added previously. Closing this issue for now, if we need any changes in this option we can have that tracked and worked upon through another ticket. :)
