### ISSUE TITLE
Introduce data retention limits

### ISSUE THREAD

**Issue by westonruter** [rtCamp/px-wp-insights#189]
When a user submits their site information, we currently store it indefinitely as I understand. In the AMP plugin v2.2 we have introduced garbage collection to remove stale validation data after a week (https://github.com/ampproject/amp-wp/pull/6763), and we should do something similar in the PX insights DB. I suggest a data retention policy of 1 month. In reality, any data we receive will likely be stale within 1 week, but having a month will allow us to go back to review recent support tickets as needed.

**Comment by dhaval-parekh** [comment]
I have created an initial PR to remove "Site Request" data that is older than a month. However, this will not remove site information itself since we are using that information in the PX insight dashboard.

**Comment by westonruter** [comment]
> However, this will not remove site information itself since we are using that information in the PX insight dashboard.

I'm not sure I understand. It removes the data but it doesn't remove it? What isn't removed?
