### ISSUE TITLE
Error on UUID report page.

### ISSUE THREAD

**Issue by dhaval-parekh** [rtCamp/px-wp-insights#193]
URL: https://insights.amp-wp.org/admin/report/uuid/ampwp-9f8179b3-f145-555a-a154-8d6bfe387cf1

![image](https://user-images.githubusercontent.com/8168027/147080400-0e75421f-e785-4337-8ec3-a5022d41a9b0.png)

**Comment by milindmore22** [comment]
I can verify that This has been fixed with #194
