### ISSUE TITLE
Escalation Path

### ISSUE THREAD

**Issue by maitreyie-chavan** [rtCamp/px-wp-insights#2]
Implement an escalation path for users of the official AMP plugin for WordPress to report issues and submit support requests

**Proposed new implementation:**

1. Move the part of code, that can send data from live sites to our data pool, to the AMP plugin.
2. A button to request support, that will send data to our server(only what user has allowed)
3. Support team can work on the issue, using that data.
4. We can even create a test site to mock the site, requesting support, using subset of plugins that are available on WordPress.org

More info on a proposed solution: https://github.com/ampproject/amp-wp/issues/5939

**Comment by dhaval-parekh** [comment]
This feature is implemented in AMP plugin version 2.2 which provide UI to the user to send a support request.

Closing this ticket.
